services:
  # Build and hot reload (-w) static Markdown files in the .posts/ directory
  jekyll-prod:
    build:
      context: .
    volumes:
      - ./jekyll:/srv/jekyll
    ports:
      - "4000:4000"
    command: "jekyll build -w"
    profiles:
      - prod
    restart: unless-stopped
  # Host the files of the site on port 8089
  nginx:
    image: nginx:latest
    depends_on:
      - jekyll-prod
    ports:
      - 8089:80
    volumes:
      - ./jekyll/_site/:/usr/share/nginx/html
    profiles:
      - prod
    restart: unless-stopped
  # Hook nginx exposed port onto the web
  cloudflared:
    image: cloudflare/cloudflared:latest
    depends_on:
      - nginx
    profiles:
      - prod
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    env_file:
      - .env
    network_mode: "host" # Ensures it can connect to services on localhost
  jekyll-dev:
    build:
      context: .
    volumes:
      - ./jekyll:/srv/jekyll
    ports:
      - "4000:4000"
    command: jekyll serve --watch --force_polling --host 0.0.0.0
    profiles:
      - dev
